FROM python:3.8-alpine

# We start with a base image set variables PYTHONUNBUFFERED and PYTHONDONTWRITEBYTECODE to 1 for logging and not creation of .pyc files respectively.
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Set the working directory inside the container to /app/backend/ for the backend.
WORKDIR /app/backend

# Copy the requirements file to the working directory and install the requirements.
COPY requirements.txt /app/backend/

# Build psycopg2-binary from source -- add required required dependencies
RUN apk add --virtual .build-deps --no-cache postgresql-dev gcc python3-dev musl-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk --purge del .build-deps

# Copy the content of our backend to the docker container
COPY . /app/backend/

# Starting command for our container
CMD python manage.py migrate && python manage.py runserver "0.0.0.0:8000"
