# Starting with a base image, it will set the working directory to /app/frontend where our code shall reside.
FROM node:16-alpine
WORKDIR /app/frontend/

# Copy package.json and package-lock.json files to working directory.
COPY package*.json /app/frontend/

# Install all the dependencies.
RUN npm install

# Copy our code content to the working directory.
COPY . /app/frontend/

# Set server starting command withCMD
CMD ["npm", "start"]
